### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Cregin** [michael-winay/YTNoCommunityPosts#8]
Youtube verison 18.49.3

See here for detailed description:https://github.com/arichorn/uYouEnhanced/issues/213

**Comment by arichornlover** [comment]
I might replace YTAsyncCollectionView with the new code below.
but I gotta test out the updated implementation first in order to help the YTNoCommunityPosts Developer
```
// Hide Community Posts - @michael-winay, @arichorn & @iCrazeiOS
%hook YTIElementRenderer
- (NSData *)elementData {
    BOOL hideCommunityPosts = [[NSUserDefaults standardUserDefaults] boolForKey:@"hide_comm_posts"];
    if (hideCommunityPosts && [[self description] containsString:@"post_base_wrapper.eml"]) {
        return nil;
    }
    return %orig;
}
%end

**Comment by arichornlover** [comment]
https://github.com/michael-winay/YTNoCommunityPosts/pull/9
